#!/usr/bin/python3

import argparse
import csv
import datetime
import json
import socket
import rospy
from time import sleep
#from std_msgs.msg import String
#from waterlinked_a50_ros_driver.msg import DVL //might have to change "waterlinked_a50 ros_driver" to my new fork bc the repo is archived. 
#from waterlinked_a50_ros_driver.msg import DVLBeam
import select

#workflow: work on reading through the parser script first. Look for important functions and classes. 
#Go to publisher next and do the same. Work on making sure that all the imports and libs work. 

def _start_dvl_socket(dvl_ip):
    dvl_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    dvl_socket.connect((dvl_ip, 16171))
    return dvl_socket
# used to start DVL by starting a TCP connection to the DVL. 
def _format_timestamps(message_type, message, time_format):
    message["log_time"] = _format_timestamp(
        message["log_time"] / 1e6,
        time_format)
    if message_type == "velocity":
        try:
            message["time_of_validity"] = _format_timestamp(
                message["time_of_validity"] / 1e6,
                time_format)
            message["time_of_transmission"] = _format_timestamp(
                message["time_of_transmission"] / 1e6,
                time_format)
        except KeyError:
            pass
    else:
        message["ts"] = _format_timestamp(message["ts"], time_format)
#used to format the timestamps of the messages.
